import "@repo/ui/globals.css";
import { cn } from "@repo/ui/lib/utils";
import type { Metadata } from "next";
import localFont from 'next/font/local'
 
const ZTtalk = localFont({
  src: [
    {
      path: '../assets/fonts/zt-talk/ZTTalk-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-Italic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-MediumItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-SemiBoldItalic.otf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../assets/fonts/zt-talk/ZTTalk-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
  ],
})


export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={cn(ZTtalk.className, 'max-w-md m-auto')}>{children}</body>
    </html>
  );
}
